FROM ubuntu:14.10

ENV PYTHON=python
ENV PIP=pip
ENTRYPOINT ["make"]
CMD []
WORKDIR /utt
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends make python python-pip
COPY data /utt/data
COPY Makefile /utt/
